# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-02 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusofticket',
            old_name='TicketStatus',
            new_name='ticket_status',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='TicketStatus',
            new_name='ticket_status',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='TicketType',
            new_name='ticket_type',
        ),
        migrations.RenameField(
            model_name='typeofticket',
            old_name='TicketType',
            new_name='ticket_type',
        ),
    ]
