# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-04 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200302_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
