# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-04 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200304_0935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusOfTicket',
            new_name='StatusTicket',
        ),
        migrations.RenameModel(
            old_name='TypeOfTicket',
            new_name='TypeTicket',
        ),
    ]
