# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-04 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20200304_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeticket',
            name='ticket_type',
            field=models.CharField(choices=[('BUG', 'bug'), ('FEATURE', 'feature')], max_length=7, unique=True),
        ),
    ]
