# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-05 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20200304_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusticket',
            name='ticket_status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='typeticket',
            name='ticket_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], max_length=7, unique=True),
        ),
    ]
