# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-09 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20200309_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(max_length=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketType'),
        ),
    ]
